[workspace]
resolver = "3"
members = ["crates/core", "crates/cli"]

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/vaital3000/storage-monitor"
authors = ["Vitaliy Pomozov"]

[workspace.dependencies]
storage-monitor-core = { path = "crates/core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }

[profile.release]
codegen-units = 1
lto = true
strip = true
