[package]
name = "storage-monitor-desktop"
version = "0.1.0"
description = "Storage Monitor desktop app"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "storage_monitor_desktop_lib"
crate-type = ["rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
storage-monitor-core = { workspace = true }
tauri = { version = "2", features = [] }
